name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        eval $(ssh-agent -s)
        ssh-add ssh_key
        ssh-keyscan -H 172.31.41.182 >> $HOME/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update System Packages
      run: |
        sudo apt-get update
      shell: bash

    - name: Install Nginx
      run: |
        sudo apt-get install nginx
      shell: bash

    - name: Install Node.js and npm
      run: |
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt-get install -y nodejs
      shell: bash

    - name: Install project dependencies
      run: |
        cd /var/www/html
        npm install
      shell: bash

    - name: Build the project
      run: |
        cd /var/www/html
        npm run build
      shell: bash

    - name: Deploy code to EC2
      run: |
        ssh -i ssh_key ubuntu@172.31.41.182 "cd ~ && git init && git remote add origin https://github.com/Abdul-fasih/test.git && git fetch origin main:main && git checkout main -- . && git clean -df"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
